src/Presentation/LeagueManager.WebUI/ViewModels/CreateTeamLeagueViewModel.cs
using LeagueManager.Application.Countries.Queries.GetCountries;
using LeagueManager.Application.Teams.Queries.GetTeams;
using LeagueManager.Application.Sports.Queries.GetTeamSports;
using LeagueManager.Application.TeamLeagues.Commands.CreateTeamLeague;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel;

namespace LeagueManager.WebUI.ViewModels
{
    public class CreateTeamLeagueViewModel : CreateTeamLeagueCommand
    {
        
        public IFormFile LogoFormFile { get; set; }
        
        public IEnumerable<TeamSportDto> TeamSports { get; set; }
        public IEnumerable<TeamDto> AllTeams { get; set; }
        public IEnumerable<CountryDto> Countries { get; set; }

        [DisplayName("Available teams")]
        public IEnumerable<string> TeamsToAdd { get; set; }

        public IEnumerable<string> SelectedTeamIds { get; set; } = new List<string>();
    }
}

src/Presentation/LeagueManager.WebUI/Controllers/CompetitionController.cs
using LeagueManager.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using LeagueManager.Infrastructure.Api;
using LeagueManager.Application.Competitions.Queries.GetCompetitions;
using LeagueManager.Application.TeamLeagues.Queries.GetTeamLeagueTable;
using LeagueManager.Application.TeamLeagues.Queries.GetTeamLeagueRounds;
using System.Linq;
using System;
using System.Net;
using LeagueManager.Application.TeamLeagueMatches.Commands.UpdateTeamLeagueMatch;
using LeagueManager.Application.TeamLeagueMatches.Commands.UpdateTeamLeagueMatchScore;
using LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatchDetails;
using LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatch;
using LeagueManager.Application.TeamCompetitor.Queries.GetPlayersForTeamCompetitor;
using LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatchEvents;
using LeagueManager.Application.TeamLeagueMatches.Commands.UpdateTeamLeagueMatchGoal;
using LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatchGoal;
using LeagueManager.Application.TeamLeagues.Queries.GetTeamLeagueCompetitors;
using LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatchLineupEntry;
using LeagueManager.Application.TeamLeagueMatches.Commands.UpdateTeamLeagueMatchLineupEntry;
using LeagueManager.WebUI.ViewModels;
using System.IO;
using LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatchSubstitution;
using LeagueManager.Application.TeamLeagueMatches.Commands.UpdateTeamLeagueMatchSubstitution;

namespace LeagueManager.WebUI.Controllers
{
    public class CompetitionController : Controller
    {
        private readonly ApiSettings apiSettings;
        private readonly ISportApi sportApi;
        private readonly ICountryApi countryApi;
        private readonly ITeamApi teamApi;
        private readonly ICompetitionApi competitionApi;

        public CompetitionController(
            IOptions<ApiSettings> apiSettings,
            ISportApi sportApi,
            ICountryApi countryApi,
            ITeamApi teamApi,
            ICompetitionApi competitionApi
        )
        {
            this.apiSettings = apiSettings.Value;
            this.sportApi = sportApi;
            this.countryApi = countryApi;
            this.teamApi = teamApi;
            this.competitionApi = competitionApi;
        }

        public async Task<IActionResult> Index()
        {
            var competitions = await competitionApi.GetCompetitions(
                new GetCompetitionsQuery()
            );

            return View(competitions);
        }

        [HttpGet("CreateTeamLeague")]
        public async Task<IActionResult> CreateTeamLeague()
        {
            var viewModel = new CreateTeamLeagueViewModel
            {
                AllTeams = await teamApi.GetTeams(),
                TeamSports = await sportApi.GetTeamSports(),
                Countries = await countryApi.GetCountries()
            };

            ViewData["TeamApiUrl"] = apiSettings.TeamApiUrl;
            ViewData["CountryApiUrl"] = apiSettings.CountryApiUrl;

            return View(viewModel);
        }

        [HttpPost("CreateTeamLeague")]
        public async Task<IActionResult> CreateTeamLeague(CreateTeamLeagueViewModel vm)
        {
            using (var memoryStream = new MemoryStream())
            {
                vm.LogoFormFile.CopyTo(memoryStream);
                vm.Logo = memoryStream.ToArray();
            }

            await competitionApi.CreateTeamLeague(vm);
            return RedirectToAction("Index");
        }

        //[Route("[controller]/{leagueName}", Name = "ViewTeamLeague")]
        [Route("[controller]/{leagueName}")]
        public async Task<IActionResult> ViewTeamLeague(string leagueName)
        {
            var vm = await competitionApi.GetTeamLeague(leagueName);
            return View(vm);
        }

        [Route("[controller]/{leagueName}/viewTeamLeagueTable")]
        public async Task<IActionResult> ViewTeamLeagueTable(string leagueName)
        {
            var table = await competitionApi.GetTeamLeagueTable(
                new GetTeamLeagueTableQuery
                {
                    LeagueName = leagueName
                }
            );

            return PartialView(table);
        }

        [Route("[controller]/{leagueName}/matches", Name = "ViewMatches")]
        public async Task<IActionResult> ViewMatches(string leagueName, string round)
        {
            var vm = await competitionApi.GetTeamLeagueRounds(
                new GetTeamLeagueRoundsQuery
                {
                    LeagueName = leagueName
                });

            return PartialView(vm);
        }

        [Route("[controller]/{leagueName}/matches/{guid}")]
        public async Task<IActionResult> ViewMatch(string leagueName, string guid)
        {
            var match = await competitionApi.GetTeamLeagueMatch(
                new GetTeamLeagueMatchQuery
                {
                    LeagueName = leagueName,
                    Guid = new Guid(guid)
                }
            );

            return PartialView(match);
        }

        [Route("[controller]/{leagueName}/editmatch/{guid}")]
        public async Task<IActionResult> EditMatch(string leagueName, string guid)
        {
            var competitors = await competitionApi.GetCompetitors(
                new GetTeamLeagueCompetitorsQuery
                {
                    LeagueName = leagueName
                });
            ViewData["Teams"] = competitors;

            var match = await competitionApi.GetTeamLeagueMatch(
                new GetTeamLeagueMatchQuery
                {
                    LeagueName = leagueName,
                    Guid = new Guid(guid)
                }
            );

            return PartialView(match);
        }

        [HttpPut("[controller]/{leagueName}/matches/{guid}")]
        public async Task<IActionResult> UpdateTeamLeagueMatch(string leagueName, Guid guid, UpdateTeamLeagueMatchDto dto)
        {
            var match = await competitionApi.UpdateTeamLeagueMatch(
                new UpdateTeamLeagueMatchCommand
                {
                    LeagueName = WebUtility.HtmlDecode(leagueName),
                    Guid = guid,
                    HomeTeam = dto.HomeTeam,
                    AwayTeam = dto.AwayTeam,
                    StartTime = dto.StartTime
                });

            return PartialView("ViewMatch", match);
        }

        [HttpPut("[controller]/{leagueName}/matches/{guid}/score")]
        public async Task<IActionResult> UpdateTeamLeagueMatchScore(string leagueName, Guid guid, UpdateTeamLeagueMatchScoreDto dto)
        {
            var match = await competitionApi.UpdateTeamLeagueMatchScore(leagueName, guid, dto);
            return PartialView("ViewMatch", match);
        }

        [HttpGet("[controller]/{leagueName}/matches/{guid}/score")]
        public async Task<IActionResult> SetScore(string leagueName, string guid)
        {
            var match = await competitionApi.GetTeamLeagueMatch(
               new GetTeamLeagueMatchQuery
               {
                   LeagueName = leagueName,
                   Guid = new Guid(guid)
               }
           );

            return PartialView(match);
        }

        [HttpGet("[controller]/{leagueName}/matches/{guid}/details")]
        public async Task<IActionResult> ViewMatchDetails(string leagueName, string guid)
        {
            var match = await competitionApi.GetTeamLeagueMatchDetails(
                new GetTeamLeagueMatchDetailsQuery
                {
                    LeagueName = leagueName,
                    Guid = new Guid(guid)
                }
            );

            ViewData["TeamLeagueApiUrl"] = apiSettings.TeamLeagueApiUrl;
            ViewData["PlayerApiUrl"] = apiSettings.PlayerApiUrl;
            ViewData["GetPlayerBaseUrl"] = $"{apiSettings.TeamLeagueApiUrl}/{leagueName}/competitors";
            ViewData["MatchBaseUrl"] = $"{apiSettings.TeamLeagueApiUrl}/{leagueName}/matches/{guid}";
            return View(match);
        }

        [HttpGet("[controller]/{leagueName}/matches/{matchGuid}/matchEntries/{teamName}/lineup/{lineupEntryGuid}")]
        public async Task<IActionResult> ViewMatchLineupEntry(string leagueName, Guid matchGuid, string teamName, Guid lineupEntryGuid)
        {
            var lineupEntry = await competitionApi.GetTeamLeagueMatchLineupEntry(
                new GetTeamLeagueMatchLineupEntryQuery
                {
                    LeagueName = leagueName,
                    MatchGuid = matchGuid,
                    LineupEntryGuid = lineupEntryGuid
                }
            );

            return PartialView(lineupEntry);
        }

        [HttpGet("[controller]/{leagueName}/matches/{matchGuid}/matchEntries/{teamName}/lineup/{lineupEntryGuid}/edit")]
        public async Task<IActionResult> EditMatchLineupEntry(string leagueName, Guid matchGuid, string teamName, Guid lineupEntryGuid)
        {
            var lineupEntry = await competitionApi.GetTeamLeagueMatchLineupEntry(
                new GetTeamLeagueMatchLineupEntryQuery
                {
                    LeagueName = leagueName,
                    MatchGuid = matchGuid,
                    LineupEntryGuid = lineupEntryGuid
                }
            );

            var players = await competitionApi.GetPlayersForTeamCompetitor(new GetPlayersForTeamCompetitorQuery
            {
                LeagueName = leagueName,
                TeamName = teamName
            });
            ViewData["Players"] = players.Select(p => p.Player);

            return PartialView(lineupEntry);
        }

        [HttpPut("[controller]/{leagueName}/matches/{matchGuid}/matchEntries/{teamName}/lineup/{lineupEntryGuid}")]

src/Presentation/LeagueManager.WebUI/Views/Competition/CreateTeamLeague.cshtml
@model LeagueManager.WebUI.ViewModels.CreateTeamLeagueViewModel
@{
    ViewData["Title"] = "Create team league";
}

<h2>@ViewData["Title"]</h2>
@using (Html.BeginForm("CreateTeamLeague", "Competition", FormMethod.Post, new { enctype="multipart/form-data"}))
{    
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label for="sports">Sports</label>
                    @Html.DropDownListFor(m => m.Sports, new SelectList(Model.TeamSports, "Name", "Name"), "--No sport selected--", new { id = "sport", @class = "form-control" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label for="countryFilter">Country</label>
                    @Html.DropDownListFor(m => m.Country, new SelectList(Model.Countries, "Name", "Name"), "--No country selected--", new { id = "country", @class = "form-control" })
                </div>
                <div class="'form-group">
                    <label for="logo">Logo</label>
                    <input asp-for="LogoFormFile" type="file" name="LogoFormFile" class="form-control">
                </div>
            </div>
        </div>
        <div class="row py-5">
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(m => m.TeamsToAdd)
                    @Html.ListBoxFor(m => m.TeamsToAdd, new SelectList(Model.AllTeams, "Name", "Name"), new { id = "teams-to-add", @class = "form-control", size = 10 })
                </div>
            </div>
            <div class="col">
                <div class="form-group">
                    @Html.LabelFor(m => m.SelectedTeams)
                    @Html.ListBoxFor(m => m.SelectedTeams, new SelectList(Model.SelectedTeams, "Name", "Name"), new { id = "selected-teams", @class = "form-control", size = 10 })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <button type="button" class="btn btn-primary add-team">Add Team(s)</button>
                <button type="button" class="btn btn-primary create-team" data-toggle="modal" data-target="#createTeamModal">Create Team</button>
            </div>
            <div class="col">
                <button type="button" class="btn btn-primary remove-team">Remove Team(s)</button>
            </div>
        </div>
        <div class="row py-3">
            <div class="col">
                <button type="submit" class="btn btn-lg btn-success">Create Team League</button>
                <div class="alert alert-success invisible" role="alert" id="create-league-alert-success"></div>
                <div class="alert alert-danger invisible" role="alert" id="create-league-alert-danger"></div>
            </div>
        </div>
    </div>
}

<!-- Modal -->
<div class="modal fade" id="createTeamModal" tabindex="-1" role="dialog" aria-labelledby="createTeamModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createTeamModalTitle">Create Team</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="team-name" class="col-form-label">Team name:</label>
                    <input type="text" class="form-control" id="team-name">
                </div>
                <div class="form-group">
                    <label for="team-country" class="col-form-label">Country name:</label>
                    <select id="country-dropdown" name="country"></select>
                </div>
                <div class="alert alert-success invisible" role="alert">
                    A simple success alert—check it out!
                </div>
                <div class="alert alert-danger invisible" role="alert"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js-save-team">Save changes</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {

            getCountries($('#country-dropdown'), "@ViewData["CountryApiUrl"]/country");
            getTeams($('#teams-to-add'), $('#selected-teams'), "@ViewData["TeamApiUrl"]/team");

            $('#country').change(function () {
                if (this.value == "--No country selected--") {
                    getTeams($('#teams-to-add'), $('#selected-teams'), "@ViewData["TeamApiUrl"]/team");
                }
                else {
                    getTeams($('#teams-to-add'), $('#selected-teams'), "@ViewData["TeamApiUrl"]/team/" + this.value);
                    $('#country-dropdown').val(this.value).change();
                }
            });

            $('#teams-to-add').on('dblclick', function () {
                moveSelectedItems($('#teams-to-add'), $('#selected-teams'));
            });

            $('.add-team').click(function () {
                moveSelectedItems($('#teams-to-add'), $('#selected-teams'));
            });

            $('#selected-teams').on('dblclick', function () {
                moveSelectedItems($('#selected-teams'), $('#teams-to-add'));
            });

            $('.remove-team').click(function () {
                moveSelectedItems($('#selected-teams'), $('#teams-to-add'));
            });

            $('.btn-success').click(function () {
                $("#selected-teams option").prop("selected", true);
            });

            $('.js-save-team').click(function (e) {
                createTeam(
                    $('#team-name'),
                    $('#country-dropdown option:selected'),
                    $('#teams-to-add'),
                    "@ViewData["TeamApiUrl"]/team"
                );
            });
        });
    </script>
}

src/Presentation/LeagueManager.WebUI/Views/Competition/EditMatchGoal.cshtml
@model LeagueManager.Application.Interfaces.Dto.IGoalDto
@{
    var players = ViewData["Players"] as IEnumerable<LeagueManager.Application.TeamCompetitor.Queries.GetPlayersForTeamCompetitor.PlayerDto>;
}

<div class="row edit-goal">
    <div class="col-2 form-group">
        @Html.LabelFor(m => m.Minute)
        @Html.TextBoxFor(m => m.Minute, new { id = $"minute-{Model.Guid}", @class = "form-control" })
    </div>
    <div class="col form-group">
        @Html.LabelFor(m => m.Player)
        <button type="button" class="btn btn-default fa fa-save js-edit-save-goal" data-guid="@Model.Guid" data-team-name="@Model.TeamMatchEntryTeamName" data-toggle="tooltip" data-placement="top" title="Save"></button>
        <button type="button" class="btn btn-default fa fa-window-close js-cancel-goal" data-guid="@Model.Guid" data-toggle="tooltip" data-placement="top" title="Cancel"></button>
        @Html.DropDownListFor(m => m.Player.FullName, new SelectList(players, "FullName", "FullName"), "--Select player--", new { id = $"player-{Model.Guid}", @class = "form-control js-select-player", @data_guid = $"{Model.Guid}" })
    </div>
</div>

src/Presentation/LeagueManager.WebUI/Views/Competition/EditMatchLineupEntry.cshtml
@model LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatchLineupEntry.LineupEntryDto

@{
    var players = ViewData["Players"] as IEnumerable<LeagueManager.Application.TeamCompetitor.Queries.GetPlayersForTeamCompetitor.PlayerDto>;
}

<div class="row edit-lineup-entry">
    <div class="col-3 form-group">
        @Html.LabelFor(m => m.PlayerNumber, "Number")
        @Html.TextBoxFor(m => m.PlayerNumber, new { id = $"number-{Model.Guid}", @class = "form-control"} )
    </div>
    <div class="col form-group">
        @Html.LabelFor(m => m.Player)
        <button type="button" class="btn btn-default fa fa-user-plus create-player" data-toggle="modal" data-guid="@Model.Guid" data-team-name="@Model.TeamName" data-target="#playerModal"></button>
        <button type="button" class="btn btn-default fa fa-save js-save-lineup-entry" data-guid="@Model.Guid" data-team-name="@Model.TeamName" data-toggle="tooltip" data-placement="top" title="Save"></button>
        <button type="button" class="btn btn-default fa fa-window-close js-cancel-lineup-entry" data-guid="@Model.Guid" data-team-name="@Model.TeamName" data-toggle="tooltip" data-placement="top" title="Cancel"></button>
        @Html.DropDownListFor(m => m.Player.FullName, new SelectList(players, "FullName", "FullName"), "--Select player--", new { id = $"player-{Model.Guid}", @class = "form-control js-select-player", @data_team_name = $"{Model.TeamName}", @data_guid = $"{Model.Guid}" })
    </div>
</div>

src/Presentation/LeagueManager.WebUI/Views/Competition/EditMatchSubstitution.cshtml
@model LeagueManager.Application.Interfaces.Dto.ISubstitutionDto
@using LeagueManager.Application.TeamCompetitor.Queries.GetPlayersForTeamCompetitor
@{
    var players = ViewData["Players"] as IEnumerable<PlayerDto>;
}

<div class="row edit-goal">
    <div class="col-2 form-group">
        @Html.LabelFor(m => m.Minute)
        @Html.TextBoxFor(m => m.Minute, new { id = $"minute-{Model.Guid}", @class = "form-control" })
    </div>
    <div class="col form-group">
        @Html.LabelFor(m => m.PlayerOut, "Player Out")
        @Html.DropDownListFor(m => m.PlayerOut.FullName, new SelectList(players, "FullName", "FullName"), "--Select player--", new { id = $"player-out-{Model.Guid}", @class = "form-control js-select-player", @data_guid = $"{Model.Guid}" })
    </div>
    <div class="col form-group">
        @Html.LabelFor(m => m.PlayerIn, "Player In")
        @Html.DropDownListFor(m => m.PlayerIn.FullName, new SelectList(players, "FullName", "FullName"), "--Select player--", new { id = $"player-in-{Model.Guid}", @class = "form-control js-select-player", @data_guid = $"{Model.Guid}" })
    </div>    
</div>
<div class="row">
    <div class="col">
        <button type="button" class="btn btn-default fa fa-save js-edit-save-sub" data-guid="@Model.Guid" data-team-name="@Model.TeamMatchEntryTeamName" data-toggle="tooltip" data-placement="top" title="Save"></button>
        <button type="button" class="btn btn-default fa fa-window-close js-cancel-sub" data-guid="@Model.Guid" data-toggle="tooltip" data-placement="top" title="Cancel"></button>
    </div>
</div>

src/Presentation/LeagueManager.WebUI/Views/Competition/SetScore.cshtml
@model LeagueManager.Application.TeamLeagueMatches.Queries.GetTeamLeagueMatch.TeamMatchDto
@using LeagueManager.Application.Interfaces.Dto

<div class="row">
    @if ((Model.Home().Team != null) && (!string.IsNullOrEmpty(Model.Home().Team.Logo)))
    {
        <div class="col-1">
            <img src="@Model.Home().Team.Logo" style="height:24px; width:24px" />
        </div>
    }
    <div class="col-5">
        <div id="home-team-@Model.Guid" class="match-team-name match-team-name--home">
            @Model.Home().Team.Name
        </div>
    </div>
    <div class="col">
        <div class="match-score match-score--home">
            <div class="form-group row">
                <div class="col">
                    @Html.LabelFor(m => m.Home().Score.Value, "Home score")
                </div>
                <div class="col">
                    @Html.EditorFor(m => m.Home().Score.Value, null, $"home-score-{Model.Guid}")
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    @if ((Model.Away().Team != null) && (!string.IsNullOrEmpty(Model.Away().Team.Logo)))
    {
        <div class="col-1">
            <img src="@Model.Away().Team.Logo" style="height:24px; width:24px" />
        </div>
    }
    <div class="col-5">
        <div id="away-team-@Model.Guid" class="match-team-name match-team-name--away">
            @Model.Away().Team.Name
        </div>
    </div>
    <div class="col">
        <div class="match-score match-score--away">
            <div class="form-group row">
                <div class="col">
                    @Html.LabelFor(m => m.Away().Score.Value, "Away score")
                </div>
                <div class="col">
                    @Html.EditorFor(m => m.Away().Score.Value, null, $"away-score-{Model.Guid}")
                </div>
            </div>
        </div>
    </div>
</div>
<div class="match-row">
    <div class="match-col">
        <button data-match-guid="@Model.Guid" class="btn btn-default fa fa-save js-save-score" data-toggle="tooltip" data-placement="top" title="Save score"></button>
        <button data-match-guid="@Model.Guid" class="btn btn-default fa fa-window-close js-cancel-edit-score" data-toggle="tooltip" data-placement="top" title="Cancel"></button>
        <div class="alert alert-success invisible" role="alert" id="alert-success-@Model.Guid"></div>
        <div class="alert alert-danger invisible" role="alert" id="alert-danger-@Model.Guid"></div>
    </div>
</div>

src/Presentation/LeagueManager.WebUI/Views/Competition/ViewGoalMatchEvent.cshtml
@model LeagueManager.Application.Interfaces.Dto.IGoalDto

<div class="row">
    @if (User.Identity.IsAuthenticated)
    {
        <div class="col-1">
            <button type="button" data-guid="@Model.Guid" data-team-name="@Model.TeamMatchEntryTeamName" class="btn btn-default btn-sm fa fa-edit js-edit-goal"></button>
        </div>
    }
    <div class="col-1">
        <i class="fa fa-futbol"></i>
    </div>
    <div class="col-1">
        <b>@($"{Model.Minute}'")</b>
    </div>
    <div class="col">
        @Model.Player.FullName
    </div>
</div>

src/Presentation/LeagueManager.WebUI/Views/Competition/ViewMatch.cshtml
@model LeagueManager.Application.Interfaces.Dto.ITeamMatchDto<ITeamMatchEntryDto>
@using LeagueManager.Application.Interfaces.Dto

@if (Model.StartTime.HasValue)
{
    <div class="row">
        <div class="col">
            @Model.StartTime.Value.ToShortDateString()
        </div>
    </div>
}
<div class="row mt-2">
    @if ((Model.Home().Team != null) && (!string.IsNullOrEmpty(Model.Home().Team.Logo)))
    {
        <div class="col-1">
            <img src="@Model.Home().Team.Logo" style="height:24px; width:24px" />
        </div>
    }
    <div class="col-5">

        @if (Model.Home().Team != null)
        {
            <div class="match-team-name match-team-name--home">
                @Model.Home().Team.Name
            </div>
        }
        else
        {
            <div class="match-team-name match-team-name--home">
                Home team not set
            </div>
        }
    </div>
    <div class="col-6 match-col-score">
        <div class="match-score match-score--home">
            <p>@(Model.Home().Score != null ? @Model.Home().Score.Value.ToString() : "-")</p>
        </div>
    </div>
</div>
<div class="row">
    @if ((Model.Away().Team != null) && (!string.IsNullOrEmpty(Model.Away().Team.Logo)))
    {
        <div class="col-1">
            <img src="@Model.Away().Team.Logo" style="height:24px; width:24px" />
        </div>
    }
    <div class="col-5">
        @if (Model.Away().Team == null)
        {
            <div class="match-team-name match-team-name--away">
                Away team not set
            </div>
        }
        else
        {
            <div class="match-team-name match-team-name--away">
                @Model.Away().Team.Name
            </div>
        }
    </div>
    <div class="col-6 match-col-score">
        <div class="match-score match-score--away">
            <p>@(Model.Away().Score != null ? @Model.Away().Score.Value.ToString() : "-")</p>
        </div>
    </div>
</div>

<div class="row mt-2">
    <div class="col">
        @if (User.Identity.IsAuthenticated)
        {
            <button data-match-guid="@Model.Guid" class="btn btn-default fa fa-edit js-edit-match" data-toggle="tooltip" data-placement="top" title="Edit fixture"></button>
            @if ((Model.Home().Team == null) || (Model.Away().Team == null))
            {
                <button data-match-guid="@Model.Guid" class="btn btn-default fa fa-futbol disabled" data-toggle="tooltip" data-placement="top" title="Set score'"></button>
            }
            else
            {
                <button data-match-guid="@Model.Guid" class="btn btn-default fa fa-futbol js-set-score" data-toggle="tooltip" data-placement="top" title="Set score"></button>
            }
        }
        @if ((Model.Home().Team == null) || (Model.Away().Team == null))
        {
            <a href="@Url.Action("ViewMatchDetails", new { leagueName = Model.TeamLeagueName,  guid = Model.Guid })" class="btn btn-default fa fa-glasses disabled" data-toggle="tooltip" data-placement="top" title="View match details"></a>
        }
        else
        {
            <a href="@Url.Action("ViewMatchDetails", new { leagueName = Model.TeamLeagueName,  guid = Model.Guid })" class="btn btn-default fa fa-glasses" data-toggle="tooltip" data-placement="top" title="View details"></a>
        }
    </div>
</div>

src/Presentation/LeagueManager.WebUI/Views/Competition/ViewMatchLineup.cshtml
@model List<LeagueManager.Application.Interfaces.Dto.ITeamMatchEntryWithDetailsDto>

<div class="row">
    @foreach (var entry in Model)
    {
        <div class="col-6">
            <div class="py-5">
                @foreach (var lineupEntry in entry.Lineup)
                {
                <div id="lineup-entry-@lineupEntry.Guid">
                    @await Html.PartialAsync("ViewMatchLineupEntry", lineupEntry)
                </div>
                }
            </div>
        </div>
    }
</div>